DROP TABLE USER_INFO;

DROP TABLE SERIES_INFO;

DROP TABLE CAST_INFO;

DROP TABLE GENRE_INFO;

DROP TABLE EPISODE_INFO;

DROP TABLE WATCH_LIST;

DROP TABLE FAVOURITES;

DROP TABLE SHARED_LIST;

CREATE TABLE USER_INFO(
	USER_ID INT PRIMARY KEY NOT NULL,
	USER_NAME CHAR(30) NOT NULL,
	EMAIL CHAR(30) NOT NULL,
	PASSWORD CHAR(30) NOT NULL
);

CREATE TABLE SERIES_INFO(
	SERIES_ID INT PRIMARY KEY NOT NULL,
	SERIES_NAME CHAR(50) NOT NULL,
	YEAR INT NOT NULL,
	RATING REAL NOT NULL	
);

CREATE TABLE CAST_INFO(
	SERIES_ID INT  NOT NULL,
	CAST_ID INT NOT NULL,
	CAST_NAME CHAR(50) NOT NULL
);

CREATE TABLE GENRE_INFO(
	SERIES_ID INT  NOT NULL,
	GENRE CHAR(50) NOT NULL	
);

CREATE TABLE EPISODE_INFO(
	SERIES_ID INT  NOT NULL,
	SEASON_NUMBER INT NOT NULL,
	NUMBER_OF_EPISODES INT NOT NULL
);

CREATE TABLE WATCH_LIST(
	USER_ID INT NOT NULL,
	SERIES_ID INT NOT NULL
);

CREATE TABLE FAVOURITES(
	USER_ID INT NOT NULL,
	SERIES_ID INT NOT NULL
);

CREATE TABLE SHARED_LIST(
	SHARED_BY INT NOT NULL,
	SHARED_TO INT NOT NULL
);

